# 数据筛选

In [1]:
import pandas as pd
import numpy as np

file = pd.read_csv('data/test_data.csv')
file.head()

connection_id  cont_1  cont_2  cont_3  cont_4  cont_5  cont_6  cont_7  \
0       cxcon_2       0     331    6085     0.0     0.0     0.0     0.0   
1       cxcon_5       0     520       0     0.0     0.0     0.0     0.0   
2       cxcon_8       0    1032       0     0.0     0.0     0.0     0.0   
3      cxcon_11       0    1032       0     0.0     0.0     0.0     0.0   
4      cxcon_14       0    1032       0     0.0     0.0     0.0     0.0   

   cont_8  cont_9  ...  cat_14  cat_15  cat_16  cat_17  cat_18  cat_19  \
0     1.0     0.0  ...       0       0       0       0       0       0   
1     1.0     0.0  ...       0       0       0       0       0       0   
2     1.0     0.0  ...       0       0       0       0       0       0   
3     1.0     0.0  ...       0       0       0       0       0       0   
4     1.0     0.0  ...       0       0       0       0       0       0   

   cat_20  cat_21  cat_22  cat_23  
0      13      13     255     255  
1     511     511     255     255  
2     511     511     255     255  
3     510     509     255     255  
4     511     511     255     255  

[5 rows x 42 columns]

In [2]:
file.shape

(91166, 42)

In [3]:
file.columns

Index(['connection_id', 'cont_1', 'cont_2', 'cont_3', 'cont_4', 'cont_5',
       'cont_6', 'cont_7', 'cont_8', 'cont_9', 'cont_10', 'cont_11', 'cont_12',
       'cont_13', 'cont_14', 'cont_15', 'cont_16', 'cont_17', 'cont_18',
       'cat_1', 'cat_2', 'cat_3', 'cat_4', 'cat_5', 'cat_6', 'cat_7', 'cat_8',
       'cat_9', 'cat_10', 'cat_11', 'cat_12', 'cat_13', 'cat_14', 'cat_15',
       'cat_16', 'cat_17', 'cat_18', 'cat_19', 'cat_20', 'cat_21', 'cat_22',
       'cat_23'],
      dtype='object')

In [4]:
less_related = file.drop('connection_id', axis=1)

In [5]:
drop_list = [ 'cat_1', 'cat_2', 'cat_3', 'cat_4', 'cat_5', 'cat_6', 'cat_7', 'cat_8',
              'cat_9', 'cat_10', 'cat_11', 'cat_12', 'cat_13', 'cat_14', 'cat_15',
              'cat_16', 'cat_17', 'cat_18', 'cat_19', 'cat_20', 'cat_21', 'cat_22',
              'cat_23']
real_data = less_related.drop(drop_list, axis=1)

In [6]:
real_data.mean(axis=0)

cont_1       44.499583
cont_2     1861.970559
cont_3      688.515115
cont_4        0.169543
cont_5        0.169616
cont_6        0.064301
cont_7        0.064299
cont_8        0.791855
cont_9        0.021109
cont_10       0.027920
cont_11       0.756498
cont_12       0.030313
cont_13       0.602494
cont_14       0.006436
cont_15       0.169583
cont_16       0.169515
cont_17       0.064585
cont_18       0.064132
dtype: float64

In [7]:
real_data.std(axis=0)

cont_1        676.749529
cont_2     297781.946527
cont_3      25226.518579
cont_4          0.374541
cont_5          0.374968
cont_6          0.244362
cont_7          0.244723
cont_8          0.388186
cont_9          0.083526
cont_10         0.139383
cont_11         0.409690
cont_12         0.107963
cont_13         0.481581
cont_14         0.041397
cont_15         0.374426
cont_16         0.374905
cont_17         0.243027
cont_18         0.242832
dtype: float64

In [8]:
drop_list2 = ['cont_1','cont_2','cont_3','cont_14']
datas = real_data.drop(drop_list2, axis=1)

In [9]:
datas.shape

(91166, 14)

# 数据扩容

In [10]:
import pandas as pd
import numpy as np

ori_data = np.array([[1, 'others'],[0, 'others'],[0, 'others'],[2, 'others'],[2, 'others'],[1, 'others']])
data = pd.DataFrame(ori_data, index=['链接{}'.format(i) for i in range(6)], columns=['传输协议','others'])
data.head(10)

传输协议  others
链接0    1  others
链接1    0  others
链接2    0  others
链接3    2  others
链接4    2  others
链接5    1  others

In [11]:
new_data = pd.get_dummies(data, columns=['传输协议'])

In [12]:
new_data = new_data.rename(columns={'传输协议_0':'ICMP','传输协议_1':'TCP','传输协议_2':'UDP'})

In [13]:
new_data

others  ICMP  TCP  UDP
链接0  others     0    1    0
链接1  others     1    0    0
链接2  others     1    0    0
链接3  others     0    0    1
链接4  others     0    0    1
链接5  others     0    1    0

In [14]:
data

传输协议  others
链接0    1  others
链接1    0  others
链接2    0  others
链接3    2  others
链接4    2  others
链接5    1  others

In [15]:
pd.concat([new_data, data], axis=1)

others  ICMP  TCP  UDP 传输协议  others
链接0  others     0    1    0    1  others
链接1  others     1    0    0    0  others
链接2  others     1    0    0    0  others
链接3  others     0    0    1    2  others
链接4  others     0    0    1    2  others
链接5  others     0    1    0    1  others

# 数据泛化

In [51]:
import pandas as pd
import numpy as np

np.set_printoptions(suppress=True)

data = np.array([443534, 5454, 2243, 928878, 10972, 87192])

## Min - Max

In [20]:
min_max_data = (data - data.min()) / (data.max() - data.min())

In [21]:
min_max_data

array([0.47622958, 0.00346523, 0.        , 1.        , 0.00942011,
       0.09167472])

## Z-score

In [22]:
d_mean = data.mean()
d_std = data.std()
z_score = (data - d_mean) / d_std

In [23]:
z_score

array([ 0.57594587, -0.70380942, -0.71318966,  1.99377264, -0.68768978,
       -0.46502966])

## Sigmoid

In [25]:
def sigmoid(x):
    return 1 / (1 + np.e ** (-x))

In [28]:
sigmoid_data = sigmoid(data)
sigmoid_data

array([1., 1., 1., 1., 1., 1.])

In [29]:
sigmoid_data = sigmoid(z_score)
sigmoid_data

array([0.64013402, 0.33096817, 0.32889443, 0.88014169, 0.33454719,
       0.38579333])

## 实战 - 数据泛化

In [41]:
file = pd.read_csv('data/test_data.csv')

print(file.cont_2.max())
print(file.cont_2.min())
print(file.cont_2.mean())

print(file.cont_5.max())
print(file.cont_5.min())
print(file.cont_5.mean())

89581520
0
1861.9705591997017
1.0
0.0
0.16961641401399657


In [44]:
d_min = file.cont_2.min()
d_max = file.cont_2.max()
new_cont_2 = (file.cont_2 - d_min) / (d_max - d_min)

In [55]:
data = new_cont_2.to_numpy()

In [58]:
data.std()

0.003324126598175045

## 数据整形
* 值变更类型
* 划分数据

In [7]:
import numpy as np
import pandas as pd

ori_data = np.array([[1,2.0,'A',True],[33,-14.27,'B',False]])
print(ori_data)
print(ori_data.shape)

[['1' '2.0' 'A' 'True']
 ['33' '-14.27' 'B' 'False']]
(2, 4)


In [2]:
ori_data.dtype

dtype('<U32')

In [3]:
for raw in range(ori_data.shape[0]):
    if ori_data[raw][2] == 'A':
        ori_data[raw][2] = 0
    elif ori_data[raw][2] == 'B':
        ori_data[raw][2] = 1
    
    if ori_data[raw][3] == 'True':
        ori_data[raw][3] = 1
    elif ori_data[raw][3] == 'False':
        ori_data[raw][3] = 0

#### 方案一

In [16]:
data = ori_data.tolist()
result = [list(map(float, data[i])) for i in range(2)]
result

#### 方案二

In [5]:
ori_data.astype(np.float32)

array([[  1.  ,   2.  ,   0.  ,   1.  ],
       [ 33.  , -14.27,   1.  ,   0.  ]], dtype=float32)

### 划分数据（划分数据集）
* 训练过程 | 建模过程 | 训练（建模）数据集
* 验证过程 | 验证过程 | 验证数据集
* 测试过程 | 测试过程 | 测试数据集

In [13]:
file = pd.read_csv('data/test_data.csv')
file.shape
ori_data = file.to_numpy()
ori_data.shape

(91166, 42)

In [12]:
raws = ori_data.shape[0]
ratio_train = 0.6
ratio_val = 0.2
ratio_test = 0.2

In [16]:
train_data = ori_data[0:int(raws * ratio_train)]
val_data = ori_data[int(raws*ratio_train):(int(raws*ratio_train)+int(raws*ratio_val))]
test_data = ori_data[-int(raws*ratio_test):]
print(train_data.shape)
print(val_data.shape)
print(test_data.shape)

(54699, 42)
(18233, 42)
(18233, 42)


In [20]:
train_data[0]

array(['cxcon_2', 0, 331, 6085, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 13, 13, 255, 255], dtype=object)

In [21]:
val_data[0]

array(['cxcon_164099', 0, 0, 0, 1.0, 1.0, 0.0, 0.0, 0.04, 0.05, 0.0, 0.07,
       0.06, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1, 13, 8, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 293, 13, 255, 17], dtype=object)

In [22]:
test_data[0]

array(['cxcon_218801', 0, 1032, 0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3, 10, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 511, 511, 255, 255], dtype=object)