# Python与Numpy

#### 美好的大学生活开始了

#### 通宵唱K打游戏，风景如画谈恋爱

![university](assets/41_university.jpg)

#### 然而机器人小Y上的大学并没有这些，只有学习，不停的学习！

In [7]:
import numpy as np

## 创建矩阵
* 纯手工创建
* 全 0 矩阵
* 全 1 矩阵
* 全随机浮点数矩阵
* 全随机整数矩阵

In [57]:
A = np.array([[1,2],[3,4]])
B = np.zeros((3,4))
C = np.ones((4,3))
D = np.random.random((3,3))
E = np.random.random((3,3)) * 900 + 100
F = np.random.randint(3, 5, (4,4))

## 矩阵运算
* 矩阵加减法
* 矩阵乘法
* 矩阵转置

### 矩阵与数、矢量的加减法

In [69]:
num = 9
array = np.array([[2],[3],[2]])
M_A = np.ones((3,3))
M_B = np.random.random((3,3))

# 数和矩阵加减法
print(num + M_A)
print(num - M_A)

# 矢量和矩阵的加减法
print(M_A + array)
print(M_A - array)

# 矩阵加减法
print(M_A + M_B)
print(M_A - M_B)

[[0.30318662 0.74063076 0.45633387]
 [0.55211552 0.61155488 0.41359627]
 [0.92585168 0.67059417 0.00598152]]


### 矩阵与数、矢量的乘法

In [79]:
num = 9
array = np.array([[2],[3],[2]])
M_A = np.ones((3,3))
M_B = np.random.random((3,3))

# 数和矩阵的乘法
print(M_A * num)

# 矢量和矩阵的积
print(M_A * array)

# 矩阵和矩阵的积
print(M_A * M_B)

# 矢量和矩阵的乘法
print(M_A.dot(array))

# 矩阵和矩阵的乘法
print(M_A.dot(M_B))

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
[[2. 2. 2.]
 [3. 3. 3.]
 [2. 2. 2.]]
[[0.43546241 0.78469826 0.94271567]
 [0.33905065 0.23244069 0.95020269]
 [0.8762751  0.291668   0.08290365]]
[[7.]
 [7.]
 [7.]]
[[1.65078816 1.30880695 1.97582201]
 [1.65078816 1.30880695 1.97582201]
 [1.65078816 1.30880695 1.97582201]]


In [81]:
MX_A = np.random.random((7,10))
MX_B = np.random.random((10,3))
MX_C = MX_A.dot(MX_B)

### 矩阵的转置

In [90]:
print(MX_C.shape)
MX_D = MX_C.T
print(MX_D.shape)

(7, 3)
(3, 7)
